name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo "Checking out repository..."

      - name: Setup Node.js
        run: echo "Setting up Node.js environment..."

      - name: Install dependencies
        run: echo "Installing dependencies..."

      - name: Run tests
        run: echo "Running tests..."

      - name: Build project
        run: echo "Building project..."

      - name: Upload build artifact
        run: echo "Uploading build artifact..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        run: echo "Downloading build artifact..."

      - name: Deploy application
        run: |
          echo "Simulating deployment..."
          DEPLOY_URL="https://myapp.example.com/$(date +%s)"
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Show Deployment URL
        run: echo "Application deployed at: $DEPLOY_URL"
