name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo "Checking out repository..."

      - name: Setup Node.js
        run: echo "Setting up Node.js environment..."

      - name: Install dependencies
        run: echo "Installing dependencies..."

      - name: Run tests
        run: echo "Running tests..."

      - name: Build project
        run: echo "Building project..."

      - name: Upload build artifact
        run: echo "Uploading build artifact..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name == 'main' && 'production' || 'dev' }}
      url: ${{ vars.ENV_URL }}
    steps:
      - name: Download build artifact
        run: echo "Downloading build artifact..."

      - name: Set Deployment URL from Secret
        env:
          DEPLOY_URL: ${{ vars.ENV_URL }}
        run: |
          echo "Using deployment URL from secret..."
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Deploy application
        run: |
          echo "Simulating deployment..."
          echo "Application deployed at: $DEPLOY_URL"

      - name: Show Deployment URL
        run: 'echo "Application is live at: $DEPLOY_URL"'
